spring:

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password:
    driverClassName: org.h2.Driver
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27018,mongo3:27019/sns?replSet=dbrs&retryWrites=true

server:
  port : 8081